/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-file' : '&#xe001;',
			'icon-print' : '&#xe002;',
			'icon-users' : '&#xe003;',
			'icon-lock' : '&#xe004;',
			'icon-binoculars' : '&#xe005;',
			'icon-download' : '&#xe007;',
			'icon-upload' : '&#xe006;',
			'icon-briefcase' : '&#xe008;',
			'icon-envelope' : '&#xe009;',
			'icon-search' : '&#xe00a;',
			'icon-file-2' : '&#xe00b;',
			'icon-profile' : '&#xe00c;',
			'icon-file-3' : '&#xe00d;',
			'icon-file-4' : '&#xe00e;',
			'icon-upload-2' : '&#xe00f;',
			'icon-download-2' : '&#xe010;',
			'icon-drawer' : '&#xe014;',
			'icon-drawer-2' : '&#xe015;',
			'icon-cabinet' : '&#xe016;',
			'icon-checkbox-partial' : '&#xe017;',
			'icon-checkbox-unchecked' : '&#xe018;',
			'icon-checkbox-checked' : '&#xe019;',
			'icon-cart' : '&#xe01e;',
			'icon-locked' : '&#xe020;',
			'icon-cloud' : '&#xe021;',
			'icon-pencil' : '&#xe024;',
			'icon-switch' : '&#xe025;',
			'icon-address-book' : '&#xe026;',
			'icon-floppy' : '&#xe027;',
			'icon-paperclip' : '&#xe02b;',
			'icon-forward' : '&#xe02c;',
			'icon-check-alt' : '&#xe02d;',
			'icon-x-altx-alt' : '&#xe02e;',
			'icon-plus-alt' : '&#xe02f;',
			'icon-minus-alt' : '&#xe030;',
			'icon-move-vertical' : '&#xe03d;',
			'icon-layers' : '&#xe042;',
			'icon-github' : '&#xe04a;',
			'icon-envelope-2' : '&#xe04b;',
			'icon-envelope-3' : '&#xe04c;',
			'icon-search-2' : '&#xe054;',
			'icon-zoom-out' : '&#xe055;',
			'icon-zoom-in' : '&#xe056;',
			'icon-binocular' : '&#xe057;',
			'icon-trashcan' : '&#xe05b;',
			'icon-user' : '&#xe05c;',
			'icon-user-2' : '&#xe05d;',
			'icon-user-3' : '&#xe05e;',
			'icon-locked-2' : '&#xe05f;',
			'icon-unlocked' : '&#xe060;',
			'icon-refresh' : '&#xe069;',
			'icon-card' : '&#xe06a;',
			'icon-cone' : '&#xe06b;',
			'icon-cart-2' : '&#xe06c;',
			'icon-icons' : '&#xe06d;',
			'icon-list' : '&#xe06e;',
			'icon-notes' : '&#xe06f;',
			'icon-notebook' : '&#xe070;',
			'icon-arrow-down' : '&#xe073;',
			'icon-arrow-up' : '&#xe074;',
			'icon-arrow-left' : '&#xe075;',
			'icon-arrow-right' : '&#xe076;',
			'icon-popout' : '&#xe07b;',
			'icon-popout-2' : '&#xe07c;',
			'icon-broadcast' : '&#xe080;',
			'icon-folder' : '&#xe081;',
			'icon-drawer-3' : '&#xe083;',
			'icon-crop' : '&#xe087;',
			'icon-bars' : '&#xe088;',
			'icon-paste' : '&#xe08f;',
			'icon-images' : '&#xe094;',
			'icon-image' : '&#xe095;',
			'icon-connection' : '&#xe097;',
			'icon-paint-format' : '&#xe09a;',
			'icon-disk' : '&#xe09c;',
			'icon-storage' : '&#xe09d;',
			'icon-keyboard' : '&#xe0a0;',
			'icon-user-4' : '&#xe0a1;',
			'icon-settings' : '&#xe0a6;',
			'icon-equalizer' : '&#xe0a7;',
			'icon-remove' : '&#xe0a8;',
			'icon-remove-2' : '&#xe0ab;',
			'icon-thumbs-up' : '&#xe0af;',
			'icon-thumbs-up-2' : '&#xe0b0;',
			'icon-spam' : '&#xe0b4;',
			'icon-checkmark-circle' : '&#xe0b5;',
			'icon-cancel-circle' : '&#xe0b6;',
			'icon-blocked' : '&#xe0b7;',
			'icon-info' : '&#xe0b8;',
			'icon-info-2' : '&#xe0b9;',
			'icon-question' : '&#xe0ba;',
			'icon-notification' : '&#xe0bb;',
			'icon-warning' : '&#xe0bc;',
			'icon-console' : '&#xe0c8;',
			'icon-code' : '&#xe0c9;',
			'icon-scissors' : '&#xe0ca;',
			'icon-crop-2' : '&#xe0cb;',
			'icon-feed' : '&#xe0ee;',
			'icon-warning-2' : '&#xe0f2;',
			'icon-move' : '&#xe0f6;',
			'icon-target' : '&#xe0f7;',
			'icon-database' : '&#xe0fa;',
			'icon-list-2' : '&#xe0fb;',
			'icon-grid' : '&#xe0fc;',
			'icon-volume' : '&#xe0fd;',
			'icon-volume-2' : '&#xe0fe;',
			'icon-tag' : '&#xe0ff;',
			'icon-earth' : '&#xe102;',
			'icon-location' : '&#xe103;',
			'icon-checkmark' : '&#xe106;',
			'icon-x' : '&#xe107;',
			'icon-denied' : '&#xe108;',
			'icon-plus' : '&#xe10d;',
			'icon-minus' : '&#xe10e;',
			'icon-move-2' : '&#xe10f;',
			'icon-move-alt1' : '&#xe110;',
			'icon-calendar' : '&#xe111;',
			'icon-tag-stroke' : '&#xe117;',
			'icon-tag-fill' : '&#xe118;',
			'icon-layers-alt' : '&#xe11d;',
			'icon-clock' : '&#xe124;',
			'icon-left-quote' : '&#xe12f;',
			'icon-right-quote' : '&#xe130;',
			'icon-left-quote-alt' : '&#xe131;',
			'icon-right-quote-alt' : '&#xe132;',
			'icon-book' : '&#xe137;',
			'icon-book-alt' : '&#xe138;',
			'icon-equalizer-2' : '&#xe139;',
			'icon-arrow-left-2' : '&#xe13c;',
			'icon-arrow-right-2' : '&#xe13d;',
			'icon-arrow-up-2' : '&#xe13e;',
			'icon-arrow-down-2' : '&#xe13f;',
			'icon-folder-2' : '&#xe142;',
			'icon-expand' : '&#xe148;',
			'icon-contract' : '&#xe149;',
			'icon-pencil-2' : '&#xe082;',
			'icon-chat' : '&#xe084;',
			'icon-comment' : '&#xe08c;',
			'icon-expand-2' : '&#xe07f;',
			'icon-contract-2' : '&#xe07e;',
			'icon-cone-2' : '&#xe0f5;',
			'icon-cog' : '&#xe112;',
			'icon-dial' : '&#xe000;',
			'icon-download-3' : '&#xe11e;',
			'icon-upload-3' : '&#xe11f;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};